<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Asigna_CriterioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'1',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'2',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'3',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'4',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'5',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'6',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'7',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'8',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'9',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'10',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'11',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'12',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'13',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'14',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'15',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'16',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'17',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'18',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'19',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'20',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'21',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'22',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'23',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'24',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'25',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'26',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'27',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'28',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'29',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'30',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'31',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'32',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'33',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'34',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'35',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'36',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'37',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'38',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'39',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'40',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'41',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'42',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'43',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'44',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'45',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'46',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'47',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'48',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'49',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'50',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'51',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'52',
            'id_criterio'=>'12',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'1',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'2',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'3',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'4',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'5',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'6',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'7',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'8',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'9',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'10',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'11',
        ]);
        DB::table('asigna_criterios')->insert([
            'id_factor'=>'53',
            'id_criterio'=>'12',
        ]);
    }
}
